name: Run thai

on:
  schedule:
    # UTCで23時, 1時, 3時, 5時, 7時, 9時, 11時, 13時
    - cron: "0 23 * * *"
    - cron: "0 1-13/2 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install gspread oauth2client feedparser selenium webdriver-manager

      - name: Run script
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: python thai.py
